### ISSUE TITLE
Permission denied error for non-administrators on accessing "My Events" page

### ISSUE THREAD

**Issue by srish** [unhangout/unhangout#454]
A possible fix would be to check the following three conditions: 
1. Show "My Events" menu item for users who are an admin of some event
2. Hide the "My Events" menu item for non-administrators
3. Show information about the permalink meeting rooms (if there are any), created by non-administrators on the "My Events" page.

**Comment by thehunmonkgroup** [comment]
in my installation, i use
```
<% if (user.isSuperuser() || user.hasPerm("createEvents")) { %>
```
in _identity.ejs
and
```
        app.get("/myevents/", ensureAuthenticated, function(req, res) {
            showEventOverview(req, res, "myevents.ejs");
        });
```
in lib/unhangout-routes.js

this works well for us, displaying the link for all users with the capacity to create events. the access check in the route is more broad, but still secure because events are filtered by permission for display.

i have other changes that make my code incompatible with producing a patch for you, but you should quite easily be able to adjust your code with what i've offered above.

**Comment by thehunmonkgroup** [comment]
#455 should address this issue.

**Comment by srish** [comment]
addressed in pull requests https://github.com/unhangout/unhangout/pull/455 and https://github.com/unhangout/unhangout/pull/475
